# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stackedwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StackedWidget(object):
    def setupUi(self, StackedWidget):
        StackedWidget.setObjectName("StackedWidget")
        StackedWidget.resize(1029, 697)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.homeButton1 = QtWidgets.QPushButton(self.page)
        self.homeButton1.setObjectName("homeButton1")
        self.verticalLayout_2.addWidget(self.homeButton1)
        self.label_2 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.toolButton = QtWidgets.QToolButton(self.page)
        font = QtGui.QFont()
        self.toolButton.setFont(font)
        self.toolButton.setStyleSheet("color:white; background-color:rgb(230,100,30);")
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_2.addWidget(self.toolButton)
        self.toolButton_2 = QtWidgets.QToolButton(self.page)
        font = QtGui.QFont()
        self.toolButton_2.setFont(font)
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout_2.addWidget(self.toolButton_2)
        self.toolButton_3 = QtWidgets.QToolButton(self.page)
        font = QtGui.QFont()
        self.toolButton_3.setFont(font)
        self.toolButton_3.setObjectName("toolButton_3")
        self.horizontalLayout_2.addWidget(self.toolButton_3)
        self.toolButton_4 = QtWidgets.QToolButton(self.page)
        font = QtGui.QFont()
        self.toolButton_4.setFont(font)
        self.toolButton_4.setObjectName("toolButton_4")
        self.horizontalLayout_2.addWidget(self.toolButton_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        StackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.homeButton2 = QtWidgets.QPushButton(self.page_2)
        self.homeButton2.setObjectName("homeButton2")
        self.verticalLayout.addWidget(self.homeButton2)
        self.label_3 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        StackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.homeButton3 = QtWidgets.QPushButton(self.page_3)
        self.homeButton3.setObjectName("homeButton3")
        self.verticalLayout_3.addWidget(self.homeButton3)
        self.label_4 = QtWidgets.QLabel(self.page_3)
        font = QtGui.QFont()
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit.setMinimumSize(QtCore.QSize(800, 50))
        font = QtGui.QFont()
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.searchButton = QtWidgets.QPushButton(self.page_3)
        self.searchButton.setMinimumSize(QtCore.QSize(0, 80))
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout.addWidget(self.searchButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        StackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.homeButton4 = QtWidgets.QPushButton(self.page_4)
        self.homeButton4.setObjectName("homeButton4")
        self.verticalLayout_4.addWidget(self.homeButton4)
        self.label_5 = QtWidgets.QLabel(self.page_4)
        font = QtGui.QFont()
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        StackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.homeButton5 = QtWidgets.QPushButton(self.page_5)
        self.homeButton5.setObjectName("homeButton5")
        self.verticalLayout_5.addWidget(self.homeButton5)
        self.label_6 = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        StackedWidget.addWidget(self.page_5)

        self.retranslateUi(StackedWidget)
        self.toolButton.clicked.connect(StackedWidget.setCurrentIndex) # type: ignore
        self.toolButton_2.clicked.connect(StackedWidget.setCurrentIndex) # type: ignore
        self.toolButton_3.clicked.connect(StackedWidget.setCurrentIndex) # type: ignore
        self.toolButton_4.clicked.connect(StackedWidget.setCurrentIndex) # type: ignore
        self.homeButton1.clicked.connect(StackedWidget.setCurrentIndex) # type: ignore
        self.homeButton2.clicked.connect(StackedWidget.setCurrentIndex) # type: ignore
        self.homeButton3.clicked.connect(StackedWidget.setCurrentIndex) # type: ignore
        self.homeButton4.clicked.connect(StackedWidget.setCurrentIndex) # type: ignore
        self.homeButton5.clicked.connect(StackedWidget.setCurrentIndex) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(StackedWidget)

    def retranslateUi(self, StackedWidget):
        _translate = QtCore.QCoreApplication.translate
        StackedWidget.setWindowTitle(_translate("StackedWidget", "BapuriFNB"))
        self.homeButton1.setText(_translate("StackedWidget", "홈(사진)"))
        self.label_2.setText(_translate("StackedWidget", " 바푸리애프앤비"))
        self.toolButton.setText(_translate("StackedWidget", "매입매출"))
        self.toolButton_2.setText(_translate("StackedWidget", "시장조사"))
        self.toolButton_3.setText(_translate("StackedWidget", "원가율"))
        self.toolButton_4.setText(_translate("StackedWidget", "발주서"))
        self.homeButton2.setText(_translate("StackedWidget", "홈(사진)"))
        self.label_3.setText(_translate("StackedWidget", " 매입매출 페이지"))
        self.homeButton3.setText(_translate("StackedWidget", "홈(사진)"))
        self.label_4.setText(_translate("StackedWidget", " 시장조사 페이지"))
        self.lineEdit.setPlaceholderText(_translate("StackedWidget", "음식 이름"))
        self.searchButton.setText(_translate("StackedWidget", "검색"))
        self.homeButton4.setText(_translate("StackedWidget", "홈(사진)"))
        self.label_5.setText(_translate("StackedWidget", " 원가율 페이지"))
        self.homeButton5.setText(_translate("StackedWidget", "홈(사진)"))
        self.label_6.setText(_translate("StackedWidget", " 발주서 페이지"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StackedWidget = QtWidgets.QStackedWidget()
    ui = Ui_StackedWidget()
    ui.setupUi(StackedWidget)
    StackedWidget.show()
    sys.exit(app.exec_())
